custom_logo: logo.png
custom_logo: /home/kadomu/git/BovReg-Reproducibility/rnaseq-nf/logo.png
custom_logo: /home/kadomu/git/BovReg-Reproducibility/rnaseq-nf/logo.png
custom_logo: /home/kadomu/git/BovReg-Reproducibility/rnaseq-nf/logo.png
